# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install a linter for code quality checks
        pip install flake8

    - name: Lint with flake8
      run: |
        # Check for Python syntax errors or undefined names (fail if any)
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        # Check for code style issues (warn but don't fail)
        flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics